module.exports = `### The build is failing

✨ Good work on this PR so far! ✨ Unfortunately, the [{{ provider }} build]({{ targetUrl }}) is failing as of {{ commit }}. Here's the output:

<!--START_LOG-->
##### \`{{ command }}\`

\`\`\`
{{{ content }}}
\`\`\`
<!--END_LOG-->

I'm sure you can fix it! If you need help, don't hesitate to ask a maintainer of the project!

{{#if lastLog}}
---
<!--START_OLD_LOGS-->
<details>
  <summary>Failed build for <code>{{ lastCommit }}</code></summary>

{{{ lastLog }}}

</details>
{{/if}}

{{{ oldLogs }}}
<!--END_OLD_LOGS-->

---

###### This comment was automagically generated by [ci-reporter](https://github.com/apps/ci-reporter). If you see a problem, open [an issue here](https://github.com/jasonetco/ci-reporter).

<!--LAST_COMMIT={{ commit }}-->`
