module.exports = `### The build is failing

{{ before }}

<!--START_LOG-->
##### \`{{ command }}\`

\`\`\`
{{{ content }}}
\`\`\`
<!--END_LOG-->

{{ after }}

{{#if lastLog}}
---
<!--START_OLD_LOGS-->
<details>
  <summary>Failed build for <code>{{ lastCommit }}</code></summary>

{{{ lastLog }}}

</details>
{{/if}}

{{{ oldLogs }}}
<!--END_OLD_LOGS-->

---

###### This comment was automagically generated by [ci-reporter](https://github.com/apps/ci-reporter). If you see a problem, open [an issue here](https://github.com/jasonetco/ci-reporter).

<!--LAST_COMMIT={{ commit }}-->`
